version: '2'
services:

  #PHP Service
  classroom_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: classroom_api
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
           - ./:/var/www
           - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  nginxclassroom_api:
    image: nginx:alpine
    restart: always
    tty: true
    ports:
      - "8087:80"
      - "447:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  #MySQL Service
  dbclassroom_api:
    image: mysql:5.7.22
    restart: always
    tty: true
    ports:
      - "3007:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
    - /var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - default

  phpmyadminclassroom_api:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - 8097:80
    links:
        - dbclassroom_api
    environment:
      PMA_HOST: ${PMA_HOST}

